name: Deploy Vue para GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependências
        working-directory: ./study-flow
        run: npm ci

      - name: Gerar build
        working-directory: ./study-flow
        run: npm run build

      - name: Configurar Pages
        uses: actions/configure-pages@v5

      - name: Upload do build
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./study-flow/dist

      - name: Publicar
        uses: actions/deploy-pages@v4